app:
  name: "bluebell"
  mode: "dev"
  port: "8080"

log: 
  level: "debug"
  filename: "bluebell.log"
  showline: true
  prefix: "bluebell"

mysql:
  host: "127.0.0.1"
  port: "3306"
  user: "root"
  password: "123456"
  dbname: "store"

# redis未写