version: "3.8"
services:
  mysql8019:
    image: "mysql:8.0.19"
    ports:
      - "13306:3306"
    command: "--default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "bluebell"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "123456"
    volumes:
      - ./init.sql:/data/application/init.sql
  redis:
    image: "hub.atomgit.com/library/redis:7.0-alpine"
    ports:
      - "16379:6379"
  bluebell_app:
    build: .
    command: sh -c "./wait-for-it.sh mysql8019:3306 redis:6379 --timeout=60 -- ./bluebell_app ./conf/config.yaml"
    depends_on:
      - mysql8019
      - redis
    ports:
      - "8080:8888"
