services:
  mysql57:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: bluebell
    command: "--default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql"
    volumes:
      - ./init.sql:/data/application/init.sql
    ports:
      - "13306:3306"
    restart: always

  redis:
    image: redis:latest
    ports:
      - "16379:6379"
    restart: always

  bluebell_app:
    build: .
    command: sh -c "./wait-for.sh mysql57:3306 redis:6379 -- ./bluebell_app ./conf/config.ini"
    depends_on:
      - mysql57
      - redis
    ports:
      - "8080:8080"
