app:
  name: "bluebell"
  mode: "dev"
  port: "8080"
  version: "v0.0.1"

log: 
  level: "debug"
  filename: "bluebell.log"
  showline: true
  prefix: "bluebell"

mysql:
  host: "mysql57"
  port: "3306"
  user: "root"
  password: "123456"
  dbname: "bluebell"

redis: 
  host: "redis"
  port: "6379"
  password: ""
  db: 0
  pool_size: 100
