app:
  name: "bluebell"
  mode: "dev"
  port: "8888"
  version: "v0.0.1"

log: 
  level: "debug"
  filename: "bluebell.log"
  showline: true
  prefix: "bluebell"

mysql:
  host: "127.0.0.1"
  port: "13306"
  user: "root"
  password: "123456"
  dbname: "bluebell"

redis: 
  host: "127.0.0.1"
  port: "26379"
  password: ""
  db: 0
  pool_size: 100
